/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Primitive Color Tokens
        'cream-50': 'var(--color-cream-50)',
        'cream-100': 'var(--color-cream-100)',
        'gray-200': 'var(--color-gray-200)',
        'gray-300': 'var(--color-gray-300)',
        'gray-400': 'var(--color-gray-400)',
        'slate-500': 'var(--color-slate-500)',
        'brown-600': 'var(--color-brown-600)',
        'charcoal-700': 'var(--color-charcoal-700)',
        'charcoal-800': 'var(--color-charcoal-800)',
        'slate-900': 'var(--color-slate-900)',
        'teal-300': 'var(--color-teal-300)',
        'teal-400': 'var(--color-teal-400)',
        'teal-500': 'var(--color-teal-500)',
        'teal-600': 'var(--color-teal-600)',
        'teal-700': 'var(--color-teal-700)',
        'teal-800': 'var(--color-teal-800)',
        'red-400': 'var(--color-red-400)',
        'red-500': 'var(--color-red-500)',
        'orange-400': 'var(--color-orange-400)',
        'orange-500': 'var(--color-orange-500)',

        // Semantic Color Tokens (Light Mode)
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        text: 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-active': 'var(--color-primary-active)',
        secondary: 'var(--color-secondary)',
        'secondary-hover': 'var(--color-secondary-hover)',
        'secondary-active': 'var(--color-secondary-active)',
        border: 'var(--color-border)',
        'btn-primary-text': 'var(--color-btn-primary-text)',
        'card-border': 'var(--color-card-border)',
        'card-border-inner': 'var(--color-card-border-inner)',
        error: 'var(--color-error)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',

        // Background color tokens
        'bg-1': 'var(--color-bg-1)',
        'bg-2': 'var(--color-bg-2)',
        'bg-3': 'var(--color-bg-3)',
        'bg-4': 'var(--color-bg-4)',
        'bg-5': 'var(--color-bg-5)',
        'bg-6': 'var(--color-bg-6)',
        'bg-7': 'var(--color-bg-7)',
        'bg-8': 'var(--color-bg-8)',
      },
      fontFamily: {
        sans: ['var(--font-family-base)', 'sans-serif'],
        mono: ['var(--font-family-mono)', 'monospace'],
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        md: 'var(--font-size-md)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      lineHeight: {
        tight: 'var(--line-height-tight)',
        normal: 'var(--line-height-normal)',
      },
      letterSpacing: {
        tight: 'var(--letter-spacing-tight)',
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '4': 'var(--space-4)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        '32': 'var(--space-32)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        base: 'var(--radius-base)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        'inset-sm': 'var(--shadow-inset-sm)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
      },
    },
  },
  plugins: [],
}