version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: portfolio-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
  frontend_data:
    driver: local
